config/routes.rb
Eventmoayo::Application.routes.draw do
  resources :coupons

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :group_products
  resources :groups

  get "session/new"
  get "session/create"
  get "session/destroy"
  resources :users do
    collection do
      get 'refresh_token'
    end
    member do
      get 'products'
    end
  end

  resources :user_products
  resources :categories

  resources :products do
    collection do
      get 'recommend'
      post 'search'
      get 'rank'
      get 'urgent'
      get 'story'
      get 'recent'
    end
  end

  root 'products#story'

  
  get 'rank', to: 'rank#index', as: 'rank'
  post 'mypeople/callback' => 'mypeople#callback'
  get 'mypeople/send_msg' => 'mypeople#send_msg'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'test' => 'test#index', as: :test_url

  

end

app/models/user_product.rb
class UserProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  attr_accessible :product_id, :user_id
  scope :get_zzim_cnt, lambda{|id| UserProduct.count(:conditions => "product_id=#{id}")}
end

app/controllers/user_products_controller.rb
class UserProductsController < ApplicationController
  before_action :set_user_product, only: [:show, :edit, :update, :destroy]

  # GET /user_products
  # GET /user_products.json
  def index
    if current_user
      @userProducts = UserProduct.find(:all, :conditions => {:user_id => current_user.id})
    end
  end

  # GET /user_products/1
  # GET /user_products/1.json
  def show
  end

  # GET /user_products/new
  def new
    @user_product = UserProduct.new
  end

  # GET /user_products/1/edit
  def edit
  end

  # POST /user_products
  # POST /user_products.json
  def create
    if !UserProduct.where(:user_id => user_product_params[:user_id], :product_id => user_product_params[:product_id]).all.blank?
      render(:json => {:status => 403 }) and return
    end
    @user_product = UserProduct.new(user_product_params)
    Product.addScoreToProduct(user_product_params[:product_id], 10)
    respond_to do |format|
      if @user_product.save
        format.html { redirect_to @user_product, notice: 'User product was successfully created.' }
        format.json { render json: @user_product, status: :created}
      else
        format.html { render action: 'new' }
        format.json { render json: @user_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_products/1
  # PATCH/PUT /user_products/1.json
  def update
    respond_to do |format|
      if @user_product.update(user_product_params)
        format.html { redirect_to @user_product, notice: 'User product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_products/1
  # DELETE /user_products/1.json
  def destroy
    if !@user_product.nil?
      Product.addScoreToProduct(@user_product.product.id, -100)
    end
    @user_product.destroy
    respond_to do |format|
      format.html { redirect_to user_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_product
      @user_product = UserProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_product_params
      params.require(:user_product).permit(:user_id, :product_id)
    end
end

app/helpers/user_products_helper.rb
module UserProductsHelper
end

app/views/user_products/_form.html.erb
<%= form_for(@user_product) do |f| %>
  <% if @user_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_product.errors.count, "error") %> prohibited this user_product from being saved:</h2>

      <ul>
      <% @user_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :prodcut_id %><br>
    <%= f.number_field :prodcut_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_products/edit.html.erb
<h1>Editing user_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_product %> |
<%= link_to 'Back', user_products_path %>

app/views/user_products/index.html.erb
<h1>Listing user_products</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Prodcut</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_products.each do |user_product| %>
      <tr>
        <td><%= user_product.user_id %></td>
        <td><%= user_product.prodcut_id %></td>
        <td><%= link_to 'Show', user_product %></td>
        <td><%= link_to 'Edit', edit_user_product_path(user_product) %></td>
        <td><%= link_to 'Destroy', user_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User product', new_user_product_path %>

app/views/user_products/new.html.erb
<h1>New user_product</h1>

<%= render 'form' %>

<%= link_to 'Back', user_products_path %>

app/views/user_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_product.user_id %>
</p>

<p>
  <strong>Prodcut:</strong>
  <%= @user_product.prodcut_id %>
</p>

<%= link_to 'Edit', edit_user_product_path(@user_product) %> |
<%= link_to 'Back', user_products_path %>