config/routes.rb
Eventmoayo::Application.routes.draw do
  resources :coupons

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :group_products
  resources :groups

  get "session/new"
  get "session/create"
  get "session/destroy"
  resources :users do
    collection do
      get 'refresh_token'
    end
    member do
      get 'products'
    end
  end

  resources :user_products
  resources :categories

  resources :products do
    collection do
      get 'recommend'
      post 'search'
      get 'rank'
      get 'urgent'
      get 'story'
      get 'recent'
    end
  end

  root 'products#story'

  
  get 'rank', to: 'rank#index', as: 'rank'
  post 'mypeople/callback' => 'mypeople#callback'
  get 'mypeople/send_msg' => 'mypeople#send_msg'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'test' => 'test#index', as: :test_url

  

end

app/controllers/mypeople_controller.rb
class MypeopleController < ApplicationController
  #before_action :set_myperson, only: [:show, :edit, :update, :destroy]

  # GET /mypeople
  # GET /mypeople.json
  protect_from_forgery except: [:callback, :send]

  def index
    @mypeople = Myperson.all
  end

  def callback
    if !params[:buddyId].nil?
      Myperson.find_or_create_by_buddy_id(:buddy_id => params[:buddyId])
    end
    render nothing: true
  end

  # GET /mypeople/1
  # GET /mypeople/1.json
  def show
  end

  # GET /mypeople/new
  def new
    @myperson = Myperson.new
  end

  # GET /mypeople/1/edit
  def edit
  end

  # POST /mypeople
  # POST /mypeople.json
  def create
    @myperson = Myperson.new(myperson_params)

    respond_to do |format|
      if @myperson.save
        format.html { redirect_to @myperson, notice: 'Myperson was successfully created.' }
        format.json { render action: 'show', status: :created, location: @myperson }
      else
        format.html { render action: 'new' }
        format.json { render json: @myperson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mypeople/1
  # PATCH/PUT /mypeople/1.json
  def update
    respond_to do |format|
      if @myperson.update(myperson_params)
        format.html { redirect_to @myperson, notice: 'Myperson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @myperson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mypeople/1
  # DELETE /mypeople/1.json
  def destroy
    @myperson.destroy
    respond_to do |format|
      format.html { redirect_to mypeople_url }
      format.json { head :no_content }
    end
  end

  def send_msg
    product = Product.top_product
    buddies = Myperson.all
    result = Array.new
    puts product.inspect
    url = url_for :controller => 'products' , :action => 'show' ,:id => product.id
    msg = "이벤트모아에서 알려드리는 핫 이벤트 소식\n이벤트명:#{product.title}\n연결링크:#{url}"
    buddies.each do |buddy|
      if !buddy[:buddy_id].nil?
        RestClient.post "https://apis.daum.net/mypeople/buddy/send.json", {'buddyId' => buddy[:buddy_id], 'content' => msg, 'apikey'=> '77529416283d858440d5fd3ecc43e9c8b464f431' }, :content_type =>'application/x-www-form-urlencoded' , :accept => "json"
      end
    end
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myperson
      @myperson = Myperson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myperson_params
      params[:myperson]
    end
end

app/helpers/mypeople_helper.rb
module MypeopleHelper
end

app/views/mypeople/_form.html.erb
<%= form_for(@myperson) do |f| %>
  <% if @myperson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myperson.errors.count, "error") %> prohibited this myperson from being saved:</h2>

      <ul>
      <% @myperson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mypeople/edit.html.erb
<h1>Editing myperson</h1>

<%= render 'form' %>

<%= link_to 'Show', @myperson %> |
<%= link_to 'Back', mypeople_path %>

app/views/mypeople/index.html.erb
<h1>Listing mypeople</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mypeople.each do |myperson| %>
      <tr>
        <td><%= link_to 'Show', myperson %></td>
        <td><%= link_to 'Edit', edit_myperson_path(myperson) %></td>
        <td><%= link_to 'Destroy', myperson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Myperson', new_myperson_path %>

app/views/mypeople/new.html.erb
<h1>New myperson</h1>

<%= render 'form' %>

<%= link_to 'Back', mypeople_path %>

app/views/mypeople/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_myperson_path(@myperson) %> |
<%= link_to 'Back', mypeople_path %>